mod chars_bool_and_unit;
mod compound_types;
mod exercises;
mod functions;
mod integers;
mod ownership;
mod referencing_and_borrowing;
mod statements_and_expressions;
fn main() {
    // exercises::ex_1::unused_var();
    // exercises::ex_2::mutate_variable();
    // exercises::ex_3::scope_fn();
    // exercises::ex_4::shadow_fn();
    // exercises::ex_4::shadow_fn_b();
    // exercises::ex_5::unused_var();
    // exercises::ex_6::destructure();
    // exercises::ex_7::destructure_assignment();
    // integers::ex_1::int_ex_1();
    // integers::ex_2::int_ex_2();
    // integers::ex_3::int_ex_3();
    // integers::ex_4::int_ex_4();
    // integers::ex_5::int_ex_5();
    // integers::ex_6::int_ex_6();
    // chars_bool_and_unit::ex_1::ex_1();
    // chars_bool_and_unit::ex_2::ex_2();
    // chars_bool_and_unit::ex_3::ex_3();
    // chars_bool_and_unit::ex_4::main();
    // chars_bool_and_unit::ex_5::main();
    // chars_bool_and_unit::ex_6::main();
    // statements_and_expressions::ex_1::main(); // wip
    // statements_and_expressions::ex_2::main();
    // statements_and_expressions::ex_3::main();
    //   functions::ex_1::main();
    // functions::ex_2::main();
    // functions::ex_3::main(); // this is intended to panic
    // functions::ex_4::main(); // wip
    // ownership::ex_1::main();
    // ownership::ex_2::main();
    // ownership::ex_3::main();
    // ownership::ex_4::main();
    // ownership::ex_5::main();
    // ownership::ex_6::main();
    // ownership::ex_7::main();
    // ownership::ex_8::main();
    // ownership::ex_9::main();
    // referencing_and_borrowing::ex_1::main();
    // referencing_and_borrowing::ex_2::main();
    // referencing_and_borrowing::ex_3::main();
    // referencing_and_borrowing::ex_4::main();
    // referencing_and_borrowing::ex_5::main();
    // referencing_and_borrowing::ex_6::main();
    // referencing_and_borrowing::ex_7::main();
    // referencing_and_borrowing::ex_8::main();
    // referencing_and_borrowing::ex_9::main();
    // referencing_and_borrowing::ex_10::main();
    // referencing_and_borrowing::ex_11::main();
    compound_types::ex_1::main();
    compound_types::ex_2::main();
    compound_types::ex_3::main();
    compound_types::ex_4::main();
    compound_types::ex_5::main();
    compound_types::ex_6::main();
    compound_types::ex_7::main();
    compound_types::ex_8::main();
    compound_types::ex_9::main();
    compound_types::ex_10::main();
    compound_types::ex_11::main();
    compound_types::ex_12::main();
}
